import { writeFileSync } from "node:fs";
import path from "node:path";
import { PLACEHOLDER_BODY_MARKERS } from "@crc/shared/bodies";
import { FORGE_BODY_PROMPT_SUFFIX } from "@crc/shared/prompts";

const repoRoot = path.join(import.meta.dirname, "..");

export const AGENT_MEMORY_PATH = path.join(repoRoot, "claude", "agent-memory.md");
export const HOOK_GUIDANCE_PATH = path.join(repoRoot, "claude", "hooks", "forge-body-guidance.js");

const GENERATED_FROM = "Generated by scripts/generate-agent-guidance.ts — run `npm run generate:agent-guidance` instead of editing this file.";

export function agentMemory(): string {
  return `<!-- ${GENERATED_FROM} -->\n\n# Posting bodies to GitHub and GitLab\n\n${FORGE_BODY_PROMPT_SUFFIX}\n`;
}

export function hookGuidanceModule(): string {
  const values = {
    FORGE_BODY_GUIDANCE: FORGE_BODY_PROMPT_SUFFIX,
    STDIN_MARKERS: [...PLACEHOLDER_BODY_MARKERS],
  };
  return `// ${GENERATED_FROM}\nmodule.exports = ${JSON.stringify(values)};\n`;
}

if (process.argv[1] && import.meta.filename === path.resolve(process.argv[1])) {
  writeFileSync(AGENT_MEMORY_PATH, agentMemory(), "utf-8");
  writeFileSync(HOOK_GUIDANCE_PATH, hookGuidanceModule(), "utf-8");
}
